### ISSUE TITLE
你好，请问有更详细的部署教程吗

### ISSUE THREAD

**Issue by AresCNZJ** [Phecda/OceanChart#3]
你好，最近有个作业要做一个与海图有关的东西，很庆幸看到了你的项目，因为没有相关的前端和建站经验，研究折腾两个晚上最终还是500错误，不得不很抱歉的请问一下有更详细的教程吗，再次感谢

**Comment by Phecda** [comment]
你好，很遗憾，没有更详细的了。这是我们当年课上的一个项目，写服务器端的那位已经忙着创业去了，无法给你更多的介绍了。谢谢关注！
